all jobs

diff --git a/.github/workflows/pipeline-ci.yml b/.github/workflows/pipeline-ci.yml
--- a/.github/workflows/pipeline-ci.yml
+++ b/.github/workflows/pipeline-ci.yml
@@ -56,6 +56,111 @@ jobs:
 
 
 
+  Deploy:
+    needs: Build
+    runs-on: 'self-hosted'
+
+    steps:
+      - name: Deploy on Docker
+        run: |
+          docker run -p 8080:80 --name ${{ github.event.repository.name }} -d giosteel88/laboratorio-final:latest
+
+      - name: Wait for readiness
+        run: | 
+          sleep 30
+  SAST:
+    runs-on: 'ubuntu-latest'
+
+    steps:
+      - name: Clone Repo
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: SonarCloud Config
+        run: |
+          sonarcloud_create_project=$(curl -s -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' \
+            -d 'name=${{ github.event.repository.name }}' \
+            -d 'project=${{ github.event.repository.name }}' \
+            -d 'organization=${{ secrets.ORG }}' \
+            -d 'visibility=public' \
+            -w "\n%{http_code}")
+          sonarcloud_create_project_status=$(tail -n1 <<< "$sonarcloud_create_project") 
+          sonarcloud_create_project_response=$(sed '$ d' <<< "$sonarcloud_create_project")
+          if [ $sonarcloud_create_project_status -eq 200 ]; then
+            echo "Project ${{ github.event.repository.name }} created successfully on Sonarcloud"
+            curl -s -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{ secrets.SONAR_PROJECT_KEY }}'
+          else
+            error_msg=$(echo "$sonarcloud_create_project_response" | jq .errors[].msg | sed -e 's/^"//' -e 's/"$//')
+            if [[ "$error_msg" == "Could not create Project, key already exists: ${{ github.event.repository.name }}" ]]; then
+              echo "Project already exists on Sonarcloud"
+            else
+              echo "::error title=API_ERROR::$error_msg"
+            fi
+          fi
+
+      - name: Install dependencies
+        run: npm install
+
+      - name: SonarCloud Scan
+        uses: sonarsource/sonarcloud-github-action@v2.3.0
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        with:
+          projectBaseDir: .
+          args: >
+            -Dsonar.organization=${{ secrets.ORG }}
+            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
+            -Dsonar.host.url=https://sonarcloud.io
+            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
+
+      - name: SonarCloud Quality Gate
+        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: https://sonarcloud.io
+
+  SCA:
+    needs: SAST
+    runs-on: 'ubuntu-latest'
+
+    steps:
+      - name: Clone Repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Install dependencies
+        run: npm install
+
+      - name: Dependency-Check
+        uses: dependency-check/Dependency-Check_Action@main
+        env:
+          JAVA_HOME: /opt/jdk
+        with:
+          project: '${{ github.event.repository.name }}'
+          path: '.'
+          format: 'JSON'
+          args: >
+            -f HTML
+            --disableYarnAudit
+
+      - name: Upload Artifact
+        uses: actions/upload-artifact@master
+        with:
+          name: Dependency-Check Report
+          path: ${{github.workspace}}/reports
+
+      - name: Evaluate Dependency-Check Report
+        run: |
+          critical_vulnerabilities=$(jq '[ .dependencies[].vulnerabilities[]? | select(.severity?|ascii_upcase == "CRITICAL")] | length' ${{github.workspace}}/reports/dependency-check-report.json)
+          high_vulnerabilities=$(jq '[ .dependencies[].vulnerabilities[]? | select(.severity?|ascii_upcase == "HIGH")] | length' ${{github.workspace}}/reports/dependency-check-report.json)
+          medium_vulnerabilities=$(jq '[ .dependencies[].vulnerabilities[]? | select(.severity?|ascii_upcase == "MEDIUM")] | length' ${{github.workspace}}/reports/dependency-check-report.json)
+          if [ $critical_vulnerabilities -gt 0 ] || [ $high_vulnerabilities -gt 0 ] || [ $medium_vulnerabilities -gt 0 ]; then
+            echo "::error title=SCA::Have been found $critical_vulnerabilities Vulnerabilities Critical, $high_vulnerabilities Vulnerabilities Major y $medium_vulnerabilities Vulnerabilities Minor."
+            exit 1
+          else
+            echo "Have not been found Vulnerabilities"
+          fi  
 
 
   DAST:
